Initial implementation of the CLoadTags instruction
CTSRD-CHERI/sail-cheri-mips pull request #1
Opened 2018-08-23 19:51 UTC by nwf

I am sure I write sail like a dunce, so feedback, especially style feedback, is more than welcome.  This is largely copied from CLoad.

One might legitimately ask about the permissions required here; it may make sense to enforce `permit_load_cap` as well as `permit_load`, as the only reasonable consumer we know of will have it anyway, but as we are not actually loading capabilities, I left it out for the moment.

2018-08-23 21:36 UTC, Jerryxia32 commented
My original intention for this instruction (and CTestSubset) is to use it as a "hardware acceleration", so from this standpoint it simply "accelerates" and does not grant additional rights. If a sequence of CLCs and CGetTags requires both permissions then probably so should CLoadTags?

Also not a sail expert but I wonder if the cache line size could be parameterizable.

2018-09-11 15:00 UTC, rmn30 commented on cheri/cheri_insts.sail
> +      if ((vAddr + 64) > getCapTop(cb_val)) then
Why 64 here? Should it not be 8 * cap_size to be consistent with below?

2018-09-11 15:02 UTC, rmn30 commented on cheri/cheri_insts.sail
> +          /* XXX This cannot possibly be idiomatic sail */
I think you should be able to use infix operator @ for vector concat and might get away with an implicit cast from bool to bit(1). Some type annotations might be required to help.

2018-09-11 15:04 UTC, rmn30 requested changes
Two major things:
1) Make sure length check is correct
2) Use @ for vector append
Not sure how to handle cache line size. Sail doesn't know anything about caches.

2018-09-11 15:04 UTC, rmn30 commented on cheri/cheri_prelude_common.sail
> +val bitvector_concat = {ocaml: "append", lem: "concat_vec"} : forall ('n : Int) ('m : Int).
This is already defined in vector_dec standard library header (not documented, sorry) and should also be possible to use @ as above.

2018-09-11 15:20 UTC, rmn30 commented
I'm wary of expanding the permission granted by permit_load to also allow loading tags. It seems safer to require both permit_load and permit_load_cap so that it would be equivalent to a bunch of clc / cgettag as @Jerryxia32  says.

2018-09-12 14:34 UTC, nwf commented
Take two.  Fixes the size check, tidies the implementation, tightens alignment requirements, and adds a test for load-cap permission.

2018-09-12 14:39 UTC, rmn30 approved these changes

2018-09-12 14:50 UTC, merged